CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Movies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TmdbId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "PictureUrl" character varying(500) NOT NULL,
    "ReleaseDate" date,
    "VoteAverage" double precision NOT NULL,
    "VoteCount" integer NOT NULL,
    "Genres" text NOT NULL,
    "OriginalLanguage" character varying(10) NOT NULL,
    "BackdropPath" character varying(500) NOT NULL,
    CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "Email" character varying(250) NOT NULL,
    "Password" character varying(255) NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "MovieLists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_MovieLists" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MovieLists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MovieListMovies" (
    "MovieId" integer NOT NULL,
    "MovieListId" integer NOT NULL,
    CONSTRAINT "PK_MovieListMovies" PRIMARY KEY ("MovieId", "MovieListId"),
    CONSTRAINT "FK_MovieListMovies_MovieLists_MovieListId" FOREIGN KEY ("MovieListId") REFERENCES "MovieLists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MovieListMovies_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MovieListMovies_MovieListId" ON "MovieListMovies" ("MovieListId");

CREATE INDEX "IX_MovieLists_UserId" ON "MovieLists" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241205224732_InitialCreate', '9.0.0');

ALTER TABLE "MovieLists" ADD "UserId1" integer;

CREATE TABLE "MovieListUsers" (
    "UserId" integer NOT NULL,
    "MovieListId" integer NOT NULL,
    CONSTRAINT "PK_MovieListUsers" PRIMARY KEY ("UserId", "MovieListId"),
    CONSTRAINT "FK_MovieListUsers_MovieLists_MovieListId" FOREIGN KEY ("MovieListId") REFERENCES "MovieLists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MovieListUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MovieLists_UserId1" ON "MovieLists" ("UserId1");

CREATE INDEX "IX_MovieListUsers_MovieListId" ON "MovieListUsers" ("MovieListId");

ALTER TABLE "MovieLists" ADD CONSTRAINT "FK_MovieLists_Users_UserId1" FOREIGN KEY ("UserId1") REFERENCES "Users" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241208172540_UpdateUserAndMovieListRelationships', '9.0.0');

COMMIT;

