version: "3.7"

services:
  backend:
    image: marijndemul16/movielist.backend
    platform: linux/amd64
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-default_user}   
      DB_PASS: ${DB_PASS:-default_pass}   
      DB_NAME: ${DB_NAME:-default_db}     
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_READ_ACCESS_TOKEN: ${TMDB_READ_ACCESS_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      DEV_MODE: ${DEV_MODE:-false}       
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: marijndemul16/movielist.frontend
    platform: linux/amd64
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt 
    environment:
      NGINX_HOST: movielist.marijndemul.nl
    networks:
      - app-network
    restart: unless-stopped
    expose:
      - "80"
      - "443"  
    depends_on:
      - backend
      - db
    entrypoint: nginx -g 'daemon off;'  

  db:
    image: postgres:13-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${DB_NAME:-default_db}
      POSTGRES_USER: ${DB_USER:-default_user}
      POSTGRES_PASSWORD: ${DB_PASS:-default_pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    platform: linux/amd64
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "30"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
