version: "3.7"

services:
  backend:
    image: marijndemul16/movielist.backend
    platform: linux/amd64
    ports: 
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-default_user}   
      DB_PASS: ${DB_PASS:-default_pass}   
      DB_NAME: ${DB_NAME:-default_db}     
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_READ_ACCESS_TOKEN: ${TMDB_READ_ACCESS_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      DEV_MODE: ${DEV_MODE:-false}      
    env_file:
      - .env 
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - ./MovieList.API:/app
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: marijndemul16/movielist.frontend
    platform: linux/amd64
    volumes:
      - ./src:/app/src  
      - /etc/letsencrypt:/etc/letsencrypt  
    ports:
      - "3000:3000" 
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${DB_NAME:-default_db}
      POSTGRES_USER: ${DB_USER:-default_user}
      POSTGRES_PASSWORD: ${DB_PASS:-default_pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=5 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
