name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: (GitHub) Checkout Code
      uses: actions/checkout@v4

    - name: (Docker) Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: (Docker) Build MovieList Frontend Docker Image
      working-directory: MovieList.Frontend
      run: |
        docker build . --platform linux/amd64 -t yourusername/movielist.frontend:latest

    - name: (Docker) Log Into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: (Docker) Push The MovieList Frontend Image To Docker Hub
      run: |
        docker push yourusername/movielist.frontend:latest

  backend:
    runs-on: ubuntu-latest

    steps:
    - name: (GitHub) Checkout Code
      uses: actions/checkout@v4

    - name: (.NET) Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: (.NET) Restore MovieList Backend Dependencies
      run: |
        dotnet restore MovieList.Backend/MovieList.sln

    - name: (.NET) Build MovieList Backend
      run: |
        dotnet build --no-restore MovieList.Backend/MovieList.sln

    - name: (.NET) Test MovieList Backend
      run: |
        dotnet test --no-build --verbosity normal MovieList.Backend/MovieList.sln

    - name: (Docker) Build MovieList Backend Docker Image
      working-directory: MovieList.Backend
      run: |
        docker build . --platform linux/amd64 -t yourusername/movielist.backend:latest

    - name: (Docker) Log Into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: (Docker) Push The MovieList Backend Image To Docker Hub
      run: |
        docker push yourusername/movielist.backend:latest
