name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup QEMU for ARM64 Emulation
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build MovieList Frontend Docker Image
        working-directory: MovieList.Frontend
        run: docker build . --platform linux/arm64 -t marijndemul16/movielist.frontend:latest

      - name: Log Into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push MovieList Frontend Image
        run: docker push marijndemul16/movielist.frontend

  backend:
    runs-on: ubuntu-latest

    env:
      DOTNET_INSTALL_DIR: "./.dotnet"

    steps:
    - name: (Github) Checkout Code
      uses: actions/checkout@v4

    - name: (.NET) Setup
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.0.x'

    - name: (.NET) Restore MovieList Backend Dependencies
      run: dotnet restore MovieList.Backend/MovieList.sln

    - name: (.NET) Build MovieList Backend
      run: dotnet build --no-restore MovieList.Backend/MovieList.sln 

    - name: (.NET) Test MovieList Backend
      run: dotnet test --no-build --verbosity normal MovieList.Backend/MovieList.sln

    - name: (Docker) Build MovieList Backend Docker Image
      working-directory: MovieList.Backend
      run: docker build . --platform linux/arm64 -t marijndemul16/movielist.backend:latest

    - name: (Docker) Log Into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: (Docker) Push The MovieList Backend Image To Docker Hub
      run: docker push marijndemul16/movielist.backend
